"""v4

Revision ID: ef4fca4242e6
Revises: 3ff5795e9efe
Create Date: 2025-11-26 15:07:05.381697

"""
from datetime import datetime
from typing import Sequence, Union

import sqlalchemy as sa
from bafser import randstr
from sqlalchemy import orm, text

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ef4fca4242e6'
down_revision: Union[str, Sequence[str], None] = '3ff5795e9efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('Quest',
                    sa.Column('name', sa.String(length=128), nullable=False),
                    sa.Column('chat_id', sa.BigInteger(), nullable=False),
                    sa.Column('chat_thread_id', sa.Integer(), nullable=False),
                    sa.Column('reward', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_Quest')),
                    sa.UniqueConstraint('id', name=op.f('uq_Quest_id')),
                    mysql_charset='utf8mb4',
                    mysql_collate='utf8mb4_unicode_ci'
                    )
    op.create_table('UserQuest',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('quest_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.ForeignKeyConstraint(['quest_id'], ['Quest.id'], name=op.f('fk_UserQuest_quest_id_Quest')),
                    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_UserQuest_user_id_User')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_UserQuest')),
                    sa.UniqueConstraint('id', name=op.f('uq_UserQuest_id')),
                    mysql_charset='utf8mb4',
                    mysql_collate='utf8mb4_unicode_ci'
                    )

    with op.batch_alter_table('Broadcast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=""))
    session = orm.Session(bind=op.get_bind())
    session.execute(text("UPDATE Broadcast SET created_at = :now"), {"now": datetime.now()})
    session.commit()
    with op.batch_alter_table('Broadcast', schema=None) as batch_op:
        batch_op.alter_column('created_at', server_default=None)

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_big', sa.String(length=16), nullable=False, server_default=""))
    users = session.execute(text("SELECT id FROM User")).all()
    existing_ids = set()
    for row in users:
        uid, = row
        bid = randstr(16)
        while bid in existing_ids:
            bid = randstr(16)
        existing_ids.add(bid)
        session.execute(text("UPDATE User SET id_big = :id_big WHERE id = :id"), {"id": uid, "id_big": bid})
    session.commit()
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('id_big', server_default=None)
        batch_op.create_index(batch_op.f('ix_User_id_big'), ['id_big'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_id_big'))
        batch_op.drop_column('id_big')

    with op.batch_alter_table('Broadcast', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.drop_table('UserQuest')
    op.drop_table('Quest')
    # ### end Alembic commands ###
