"""v2

Revision ID: 8cf994e29ef5
Revises: 7ed0585be0ff
Create Date: 2025-07-19 20:48:40.342610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '8cf994e29ef5'
down_revision: Union[str, None] = '7ed0585be0ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Broadcast',
        sa.Column('chat_id', sa.BigInteger(), nullable=False),
        sa.Column('chat_thread_id', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(length=256), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_Broadcast')),
        sa.UniqueConstraint('id', name=op.f('uq_Broadcast_id')),
        mysql_charset='utf8mb4',
        mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###

    bind = op.get_bind()
    session = orm.Session(bind=bind)
    config = session.execute(text("SELECT chat_id, chat_thread_id FROM Config")).first()
    if config:
        chat_id = config[0]
        chat_thread_id = config[1]
        if chat_id:
            session.execute(text("INSERT INTO Broadcast (chat_id, chat_thread_id, title) VALUES (:chat_id, :chat_thread_id, :title)"), {
                "chat_id": chat_id,
                "chat_thread_id": chat_thread_id,
                "title": "",
            })
            session.commit()

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Config', schema=None) as batch_op:
        batch_op.drop_column('chat_thread_id')
        batch_op.drop_column('chat_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_id', sa.BIGINT(), nullable=True))
        batch_op.add_column(sa.Column('chat_thread_id', sa.INTEGER(), nullable=True))

    op.drop_table('Broadcast')
    # ### end Alembic commands ###
