"""v3

Revision ID: 3ff5795e9efe
Revises: 8cf994e29ef5
Create Date: 2025-10-05 22:05:09.167291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '3ff5795e9efe'
down_revision: Union[str, Sequence[str], None] = '8cf994e29ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_state',
    sa.Column('initialized', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_db_state')),
    sa.UniqueConstraint('id', name=op.f('uq_db_state_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('Msg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_to_id', sa.Integer(), nullable=True))
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=512),
               existing_nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_Msg_reply_to_id_Msg'), 'Msg', ['reply_to_id'], ['id'])
        batch_op.drop_column('date')

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###

    bind = op.get_bind()
    session = orm.Session(bind=bind)
    session.execute(text("INSERT INTO db_state (id, initialized) VALUES (1, 1)"))
    session.commit()

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('Msg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_Msg_reply_to_id_Msg'), type_='foreignkey')
        batch_op.alter_column('text',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.drop_column('reply_to_id')

    op.drop_table('db_state')
    # ### end Alembic commands ###
