"""v5

Revision ID: dcecc5cf85fb
Revises: ef4fca4242e6
Create Date: 2025-11-27 12:54:10.515680

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dcecc5cf85fb'
down_revision: Union[str, Sequence[str], None] = 'ef4fca4242e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserPoints',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('points', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_UserPoints_user_id_User')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_UserPoints')),
                    sa.UniqueConstraint('id', name=op.f('uq_UserPoints_id')),
                    mysql_charset='utf8mb4',
                    mysql_collate='utf8mb4_unicode_ci'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserPoints')
    # ### end Alembic commands ###
